# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "default"
defaultContentLanguage = "en"

# Hugo settings
disableHugoGeneratorInject = true
disableKinds = ["rss", "section", "sitemap", "taxonomy", "term"]
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGoogleAnalytics = false

[languages]
  [languages.en]
    title = "MIA Doors"
    locale = "en"
    [languages.en.params]
      description = "Sliding Doors, Repairs, Installations"

[privacy]
  [privacy.googleanalytics]
    [privacy.googleanalytics.service]
      disable = true
